{
 "title": "VMware ESXi",
 "description": "VMware ESXi single instance graphs ( https://github.com/DenGontsov/vmware-exporter-grafana-dashboard )",
 "tags": [
  "vmware",
  "esxi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "VmHost",
    "label": "VmHost",
    "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
   },
   {
    "name": "Vm",
    "label": "Vm",
    "query": {
     "query": "label_values(vmware_vm_power_state,vm_name)"
    }
   },
   {
    "name": "DS",
    "label": "DS",
    "query": {
     "query": "label_values(vmware_datastore_freespace_size,ds_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "VMs Power Status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vmware_vm_power_state{host_name=~\"$VmHost\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_product_info{host_name=~\"$VmHost\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_hardware_info{host_name=~\"$VmHost\"}) ",
     "legendFormat": "{{ hardware_model }}"
    }
   ]
  },
  {
   "title": "Build",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_product_info{host_name=~\"$VmHost\"})",
     "legendFormat": "{{ build }}"
    }
   ]
  },
  {
   "title": "Cpu Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_hardware_info{host_name=~\"$VmHost\"}) ",
     "legendFormat": "{{ hardware_cpu_model }}"
    }
   ]
  },
  {
   "title": "ESXi host uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-vmware_host_boot_timestamp_seconds{host_name=~\"$VmHost\"} "
    }
   ]
  },
  {
   "title": "Cpu Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_num_cpu{host_name=~\"$VmHost\"})"
    }
   ]
  },
  {
   "title": "Memory Capaciy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_memory_max{host_name=~\"$VmHost\"})"
    }
   ]
  },
  {
   "title": "Host Memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$VmHost\"}) * 100 / (vmware_host_memory_max{host_name=~\"$VmHost\"})"
    }
   ]
  },
  {
   "title": "Host CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_host_cpu_usagemhz_average{host_name=~\"$VmHost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$VmHost\"})"
    }
   ]
  },
  {
   "title": "Datastore free space %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_datastore_freespace_size{ds_name=\"$DS\"} / vmware_datastore_capacity_size{ds_name=\"$DS\"}) * 100",
     "legendFormat": "Free %"
    },
    {
     "expr": "vmware_datastore_freespace_size{ds_name=\"$DS\"}",
     "legendFormat": "Free (bytes)"
    },
    {
     "expr": "vmware_datastore_capacity_size{ds_name=\"$DS\"}",
     "legendFormat": "Capacity (bytes)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(vmware_host_cpu_usagemhz_average{host_name=~\"$VmHost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$VmHost\"})",
       "legendFormat": "Cpu Usage"
      },
      {
       "expr": "(vmware_host_cpu_demand_average{host_name=~\"$VmHost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$VmHost\"})",
       "legendFormat": "CPU Demand"
      }
     ]
    },
    {
     "title": "Host Cpu Contention",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "vmware_host_cpu_ready_summation{host_name=~\"$VmHost\"}/200",
       "legendFormat": "Cpu Ready"
      },
      {
       "expr": "vmware_host_cpu_costop_summation{host_name=~\"$VmHost\"}/200",
       "legendFormat": "Cpu Co-Stop"
      },
      {
       "expr": "vmware_host_cpu_swapwait_summation{host_name=~\"$VmHost\"}/200",
       "legendFormat": "Cpu Swap Wait"
      }
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(vmware_host_mem_usage_average{host_name=~\"$VmHost\"}) * 100 / (vmware_host_memory_max{host_name=~\"$VmHost\"})",
       "legendFormat": "Memory Consumed"
      },
      {
       "expr": "(vmware_host_mem_active_average{host_name=~\"$VmHost\"})/1024 * 100 / (vmware_host_memory_max{host_name=~\"$VmHost\"})",
       "legendFormat": "Memory Active"
      }
     ]
    },
    {
     "title": "Host Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "vmware_host_mem_vmmemctl_average{host_name=~\"$VmHost\"}",
       "legendFormat": "Memory Balloon"
      },
      {
       "expr": "vmware_host_mem_latency_average{host_name=~\"$VmHost\"}",
       "legendFormat": "Memory Latency"
      },
      {
       "expr": "vmware_host_mem_swapinRate_average{host_name=~\"$VmHost\"}",
       "legendFormat": "Memory SwapInRate"
      },
      {
       "expr": "vmware_host_mem_swapoutRate_average{host_name=~\"$VmHost\"}",
       "legendFormat": "Memory SwapOutRate"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "vmware_host_net_usage_average{host_name=~\"$VmHost\"}",
       "legendFormat": "Total Usage"
      },
      {
       "expr": "vmware_host_net_bytesRX_average{host_name=~\"$VmHost\"}",
       "legendFormat": "Usage RX"
      },
      {
       "expr": "vmware_host_net_bytesTX_average{host_name=~\"$VmHost\"}",
       "legendFormat": "Usage TX"
      },
      {
       "expr": "sum(vmware_vm_net_broadcastRx_summation{host_name=~\"$VmHost\"})",
       "legendFormat": "Broadcast RX"
      },
      {
       "expr": "sum(vmware_vm_net_broadcastTx_summation{host_name=~\"$VmHost\"})",
       "legendFormat": "Broadcast TX"
      },
      {
       "expr": "sum(vmware_vm_net_multicastRx_summation{host_name=~\"$VmHost\"})",
       "legendFormat": "Multicast RX"
      },
      {
       "expr": "sum(vmware_vm_net_multicastTx_summation{host_name=~\"$VmHost\"})",
       "legendFormat": "Multicast TX"
      }
     ]
    },
    {
     "title": "Host Network Contention",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vmware_host_net_errorRX_summation{host_name=~\"$VmHost\"} OR vector(0)",
       "legendFormat": "Error RX"
      },
      {
       "expr": "vmware_host_net_errorTX_summation{host_name=~\"$VmHost\"} OR vector(0) ",
       "legendFormat": "Error TX"
      },
      {
       "expr": "vmware_host_net_droppedTX_summation{host_name=~\"$VmHost\"} OR vector(0)",
       "legendFormat": "Dropped TX"
      },
      {
       "expr": "vmware_host_net_droppedRX_summation{host_name=~\"$VmHost\"} OR vector(0)",
       "legendFormat": "Dropped RX"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk R\\W Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk R/W Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "vmware_host_disk_read_average{host_name=~\"$VmHost\"}+vmware_host_disk_write_average{host_name=~\"$VmHost\"}",
       "legendFormat": "Disk Read and Write"
      },
      {
       "expr": "vmware_host_disk_read_average{host_name=~\"$VmHost\"}",
       "legendFormat": "Disk Read"
      },
      {
       "expr": "vmware_host_disk_write_average{host_name=~\"$VmHost\"}",
       "legendFormat": "Disk Write"
      }
     ]
    }
   ]
  },
  { "title": "$Vm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "Vm" },
  {
   "title": "VM Power State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$Vm\"}"
    }
   ]
  },
  {
   "title": "VM Boot Timestamp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$Vm\"}) / 3600\n",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VM CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_usage_average{vm_name=\"$Vm\"} / 1000"
    }
   ]
  },
  {
   "title": "VM Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$Vm\"}"
    }
   ]
  },
  {
   "title": "VM Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$Vm\"}"
    }
   ]
  }
 ]
}